spring:
    profiles:
        active: dev


---
server:
    port: 8201
spring:
    profiles: dev
    application:
        name: spring-cloud-provider-dept
# 注册服务到eureka
eureka:
    client:
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka/
---
server:
    port: 8202
spring:
    profiles: test
    application:
        name: spring-cloud-provider-dept
# 注册服务到eureka
eureka:
    client:
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka/








