server:
    port: 7003

# 注册中心
eureka:
    instance:
        hostname: eureka7003.com # 服务端的实例名称
    client:
        register-with-eureka: false # 是否向ureka注册中心注册自己(这个模块本身是服务器,所以不需要)
        fetch-registry: false # false表示自己是一个注册中心
        service-url: # eureka监控页面
            defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/













